[build]
  functions = "netlify/functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/api/upload"
  to = "/.netlify/functions/upload"
  status = 200

[[redirects]]
  from = "/*"
  to = "https://files.catbox.moe/:splat"
  status = 200
